# Generated by Django 2.1.2 on 2018-11-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=15)),
                ('fotografia', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=60)),
                ('rut', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.IntegerField()),
                ('region', models.CharField(max_length=30)),
                ('comuna', models.CharField(max_length=30)),
                ('casa', models.CharField(max_length=15)),
            ],
        ),
    ]
